#!/usr/bin/env bash
set -euo pipefail
ROOT="/home/mmoslem3/scratch/attack_if"
mkdir -p "$ROOT/sbatch/logs"
sbatch "$ROOT/sbatch/defense/defense_001_convnet_fc_dog_bird_epic_random_ours_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_002_convnet_fc_dog_bird_epic_ours_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_003_convnet_gradmatch_dog_bird_epic_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_004_convnet_sapa_dog_bird_epic_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_005_convnet_fc_dog_bird_friends_random_ours_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_006_convnet_fc_dog_bird_friends_ours_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_007_convnet_gradmatch_dog_bird_friends_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_008_convnet_sapa_dog_bird_friends_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_009_resnet20_fc_dog_bird_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_010_resnet20_fc_dog_bird_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_011_resnet20_gradmatch_dog_bird_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_012_resnet20_gradmatch_dog_bird_epic_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_013_resnet20_sapa_dog_bird_epic_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_014_resnet20_fc_dog_bird_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_015_resnet20_fc_dog_bird_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_016_resnet20_gradmatch_dog_bird_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_017_resnet20_gradmatch_dog_bird_friends_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_018_resnet20_sapa_dog_bird_friends_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_019_vgg13_gradmatch_dog_bird_epic_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_020_vgg13_gradmatch_dog_bird_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_021_vgg13_sapa_dog_bird_epic_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_022_vgg13_sapa_dog_bird_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_023_vgg13_gradmatch_dog_bird_friends_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_024_vgg13_gradmatch_dog_bird_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_025_vgg13_sapa_dog_bird_friends_random_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_026_vgg13_sapa_dog_bird_friends_dpp_j.sh"
sleep 1
