#!/usr/bin/env bash
set -euo pipefail
ROOT="/home/mmoslem3/scratch/attack_if"
mkdir -p "$ROOT/sbatch/logs"
sbatch "$ROOT/sbatch/attack/attack_001_convnet_gradmatch_dog_bird_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_002_convnet_gradmatch_dog_bird_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_003_convnet_gradmatch_dog_bird_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_004_convnet_sapa_dog_bird_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_005_convnet_sapa_dog_bird_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_006_convnet_sapa_dog_bird_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_007_convnet_gradmatch_frog_airplane_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_008_convnet_gradmatch_frog_airplane_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_009_convnet_gradmatch_frog_airplane_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_010_convnet_sapa_frog_airplane_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_011_convnet_sapa_frog_airplane_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_012_convnet_sapa_frog_airplane_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_013_resnet20_fc_dog_bird_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_014_resnet20_fc_dog_bird_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_015_resnet20_fc_dog_bird_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_016_resnet20_gradmatch_dog_bird_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_017_resnet20_gradmatch_dog_bird_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_018_resnet20_sapa_dog_bird_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_019_resnet20_sapa_dog_bird_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_020_resnet20_fc_frog_airplane_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_021_resnet20_fc_frog_airplane_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_022_resnet20_fc_frog_airplane_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_023_resnet20_gradmatch_frog_airplane_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_024_resnet20_gradmatch_frog_airplane_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_025_resnet20_gradmatch_frog_airplane_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_026_resnet20_sapa_frog_airplane_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_027_resnet20_sapa_frog_airplane_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_028_resnet20_sapa_frog_airplane_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_029_vgg13_fc_dog_bird_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_030_vgg13_fc_dog_bird_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_031_vgg13_fc_dog_bird_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_032_vgg13_gradmatch_dog_bird_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_033_vgg13_gradmatch_dog_bird_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_034_vgg13_gradmatch_dog_bird_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_035_vgg13_sapa_dog_bird_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_036_vgg13_sapa_dog_bird_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_037_vgg13_sapa_dog_bird_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_038_vgg13_fc_frog_airplane_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_039_vgg13_fc_frog_airplane_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_040_vgg13_fc_frog_airplane_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_041_vgg13_gradmatch_frog_airplane_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_042_vgg13_gradmatch_frog_airplane_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_043_vgg13_gradmatch_frog_airplane_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_044_vgg13_sapa_frog_airplane_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_045_vgg13_sapa_frog_airplane_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_046_vgg13_sapa_frog_airplane_dpp_j.sh"
sleep 1
