#!/bin/sh
set -eu
ROOT="/home/mmoslem3/scratch/attack_if"
mkdir -p "$ROOT/sbatch/logs"
sbatch "$ROOT/sbatch/attack/attack_001_convnet_gradmatch_dog_bird_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_002_convnet_gradmatch_dog_bird_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_003_convnet_gradmatch_dog_bird_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_004_convnet_gradmatch_dog_bird_b0_02_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_005_convnet_gradmatch_dog_bird_b0_04_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_006_convnet_gradmatch_dog_bird_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_007_convnet_gradmatch_dog_bird_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_008_convnet_gradmatch_dog_bird_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_009_convnet_gradmatch_dog_bird_b0_02_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_010_convnet_gradmatch_dog_bird_b0_02_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_011_convnet_sapa_dog_bird_b0_02_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_012_convnet_sapa_dog_bird_b0_04_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_013_convnet_sapa_dog_bird_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_014_convnet_sapa_dog_bird_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_015_convnet_sapa_dog_bird_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_016_convnet_sapa_dog_bird_b0_02_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_017_convnet_sapa_dog_bird_b0_02_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_018_convnet_gradmatch_frog_airplane_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_019_convnet_gradmatch_frog_airplane_b0_02_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_020_convnet_gradmatch_frog_airplane_b0_04_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_021_convnet_gradmatch_frog_airplane_b0_02_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_022_convnet_gradmatch_frog_airplane_b0_02_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_023_convnet_sapa_frog_airplane_b0_02_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_024_convnet_sapa_frog_airplane_b0_04_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_025_convnet_sapa_frog_airplane_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_026_convnet_sapa_frog_airplane_b0_02_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_027_convnet_sapa_frog_airplane_b0_02_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_028_resnet20_fc_dog_bird_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_029_resnet20_fc_dog_bird_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_030_resnet20_fc_dog_bird_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_031_resnet20_fc_dog_bird_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_032_resnet20_fc_dog_bird_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_033_resnet20_fc_dog_bird_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_034_resnet20_fc_dog_bird_b0_001_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_035_resnet20_gradmatch_dog_bird_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_036_resnet20_gradmatch_dog_bird_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_037_resnet20_gradmatch_dog_bird_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_038_resnet20_gradmatch_dog_bird_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_039_resnet20_gradmatch_dog_bird_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_040_resnet20_gradmatch_dog_bird_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_041_resnet20_gradmatch_dog_bird_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_042_resnet20_sapa_dog_bird_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_043_resnet20_sapa_dog_bird_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_044_resnet20_sapa_dog_bird_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_045_resnet20_sapa_dog_bird_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_046_resnet20_sapa_dog_bird_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_047_resnet20_sapa_dog_bird_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_048_resnet20_sapa_dog_bird_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_049_resnet20_fc_frog_airplane_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_050_resnet20_fc_frog_airplane_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_051_resnet20_fc_frog_airplane_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_052_resnet20_fc_frog_airplane_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_053_resnet20_fc_frog_airplane_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_054_resnet20_fc_frog_airplane_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_055_resnet20_fc_frog_airplane_b0_001_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_056_resnet20_gradmatch_frog_airplane_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_057_resnet20_gradmatch_frog_airplane_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_058_resnet20_gradmatch_frog_airplane_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_059_resnet20_gradmatch_frog_airplane_b0_001_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_060_resnet20_sapa_frog_airplane_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_061_resnet20_sapa_frog_airplane_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_062_resnet20_sapa_frog_airplane_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_063_resnet20_sapa_frog_airplane_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_064_resnet20_sapa_frog_airplane_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_065_resnet20_sapa_frog_airplane_b0_001_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_066_vgg13_fc_dog_bird_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_067_vgg13_fc_dog_bird_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_068_vgg13_fc_dog_bird_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_069_vgg13_fc_dog_bird_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_070_vgg13_fc_dog_bird_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_071_vgg13_fc_dog_bird_b0_001_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_072_vgg13_gradmatch_dog_bird_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_073_vgg13_gradmatch_dog_bird_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_074_vgg13_gradmatch_dog_bird_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_075_vgg13_gradmatch_dog_bird_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_076_vgg13_gradmatch_dog_bird_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_077_vgg13_gradmatch_dog_bird_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_078_vgg13_gradmatch_dog_bird_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_079_vgg13_sapa_dog_bird_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_080_vgg13_sapa_dog_bird_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_081_vgg13_sapa_dog_bird_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_082_vgg13_sapa_dog_bird_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_083_vgg13_sapa_dog_bird_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_084_vgg13_sapa_dog_bird_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_085_vgg13_sapa_dog_bird_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_086_vgg13_fc_frog_airplane_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_087_vgg13_fc_frog_airplane_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_088_vgg13_fc_frog_airplane_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_089_vgg13_fc_frog_airplane_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_090_vgg13_fc_frog_airplane_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_091_vgg13_fc_frog_airplane_b0_002_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_092_vgg13_fc_frog_airplane_b0_005_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_093_vgg13_fc_frog_airplane_b0_001_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_094_vgg13_gradmatch_frog_airplane_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_095_vgg13_gradmatch_frog_airplane_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_096_vgg13_gradmatch_frog_airplane_b0_01_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_097_vgg13_gradmatch_frog_airplane_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_098_vgg13_gradmatch_frog_airplane_b0_001_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_099_vgg13_sapa_frog_airplane_b0_001_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_100_vgg13_sapa_frog_airplane_b0_002_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_101_vgg13_sapa_frog_airplane_b0_005_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_102_vgg13_sapa_frog_airplane_b0_001_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_103_vgg13_sapa_frog_airplane_b0_001_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_104_convnet_gradmatch_dog_bird_b0_04_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_105_convnet_gradmatch_dog_bird_b0_04_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_106_convnet_sapa_dog_bird_b0_04_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_107_convnet_sapa_dog_bird_b0_04_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_108_convnet_gradmatch_frog_airplane_b0_04_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_109_convnet_gradmatch_frog_airplane_b0_04_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_110_convnet_sapa_frog_airplane_b0_04_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_111_convnet_sapa_frog_airplane_b0_04_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_112_resnet20_fc_dog_bird_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_113_resnet20_gradmatch_dog_bird_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_114_resnet20_sapa_dog_bird_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_115_resnet20_fc_frog_airplane_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_116_resnet20_fc_frog_airplane_b0_01_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_117_resnet20_gradmatch_frog_airplane_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_118_resnet20_gradmatch_frog_airplane_b0_01_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_119_resnet20_sapa_frog_airplane_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_120_resnet20_sapa_frog_airplane_b0_01_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_121_vgg13_gradmatch_dog_bird_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_122_vgg13_gradmatch_dog_bird_b0_01_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_123_vgg13_sapa_dog_bird_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_124_vgg13_sapa_dog_bird_b0_01_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_125_vgg13_fc_frog_airplane_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_126_vgg13_fc_frog_airplane_b0_01_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_127_vgg13_gradmatch_frog_airplane_b0_01_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_128_vgg13_sapa_frog_airplane_b0_01_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/attack/attack_129_vgg13_sapa_frog_airplane_b0_01_dpp_j.sh"
sleep 1
