#!/bin/sh
set -eu
ROOT="/home/mmoslem3/scratch/attack_if"
mkdir -p "$ROOT/sbatch/logs"
sbatch "$ROOT/sbatch/defense/defense_001_convnet_fc_dog_bird_b0_01_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_002_convnet_fc_dog_bird_b0_01_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_003_convnet_fc_dog_bird_b0_01_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_004_convnet_fc_dog_bird_b0_02_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_005_convnet_fc_dog_bird_b0_02_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_006_convnet_fc_dog_bird_b0_02_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_007_convnet_fc_dog_bird_b0_01_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_008_convnet_fc_dog_bird_b0_01_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_009_convnet_fc_dog_bird_b0_02_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_010_convnet_fc_dog_bird_b0_02_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_011_convnet_gradmatch_dog_bird_b0_02_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_012_convnet_gradmatch_dog_bird_b0_02_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_013_convnet_sapa_dog_bird_b0_02_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_014_convnet_sapa_dog_bird_b0_02_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_015_convnet_fc_dog_bird_b0_01_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_016_convnet_fc_dog_bird_b0_01_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_017_convnet_fc_dog_bird_b0_01_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_018_convnet_fc_dog_bird_b0_02_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_019_convnet_fc_dog_bird_b0_02_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_020_convnet_fc_dog_bird_b0_02_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_021_convnet_fc_dog_bird_b0_01_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_022_convnet_fc_dog_bird_b0_01_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_023_convnet_fc_dog_bird_b0_02_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_024_convnet_fc_dog_bird_b0_02_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_025_convnet_gradmatch_dog_bird_b0_02_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_026_convnet_gradmatch_dog_bird_b0_02_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_027_convnet_sapa_dog_bird_b0_02_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_028_convnet_sapa_dog_bird_b0_02_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_029_resnet20_fc_dog_bird_b0_01_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_030_resnet20_fc_dog_bird_b0_01_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_031_resnet20_gradmatch_dog_bird_b0_002_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_032_resnet20_gradmatch_dog_bird_b0_01_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_033_resnet20_gradmatch_dog_bird_b0_01_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_034_resnet20_sapa_dog_bird_b0_01_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_035_resnet20_sapa_dog_bird_b0_01_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_036_resnet20_fc_dog_bird_b0_01_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_037_resnet20_fc_dog_bird_b0_01_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_038_resnet20_gradmatch_dog_bird_b0_002_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_039_resnet20_gradmatch_dog_bird_b0_01_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_040_resnet20_gradmatch_dog_bird_b0_01_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_041_resnet20_sapa_dog_bird_b0_01_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_042_resnet20_sapa_dog_bird_b0_01_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_043_vgg13_gradmatch_dog_bird_b0_005_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_044_vgg13_gradmatch_dog_bird_b0_005_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_045_vgg13_gradmatch_dog_bird_b0_01_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_046_vgg13_gradmatch_dog_bird_b0_01_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_047_vgg13_gradmatch_dog_bird_b0_005_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_048_vgg13_sapa_dog_bird_b0_005_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_049_vgg13_sapa_dog_bird_b0_005_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_050_vgg13_sapa_dog_bird_b0_01_epic_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_051_vgg13_sapa_dog_bird_b0_01_epic_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_052_vgg13_sapa_dog_bird_b0_005_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_053_vgg13_gradmatch_dog_bird_b0_005_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_054_vgg13_gradmatch_dog_bird_b0_005_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_055_vgg13_gradmatch_dog_bird_b0_01_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_056_vgg13_gradmatch_dog_bird_b0_01_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_057_vgg13_gradmatch_dog_bird_b0_005_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_058_vgg13_sapa_dog_bird_b0_005_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_059_vgg13_sapa_dog_bird_b0_005_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_060_vgg13_sapa_dog_bird_b0_01_friends_random_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_061_vgg13_sapa_dog_bird_b0_01_friends_dpp_std.sh"
sleep 1
sbatch "$ROOT/sbatch/defense/defense_062_vgg13_sapa_dog_bird_b0_005_friends_dpp_j.sh"
sleep 1
