#!/bin/sh
# Submit defense cells that were absent from the original 62-job set.
set -eu
ROOT="/home/mmoslem3/scratch/attack_if"
mkdir -p "$ROOT/sbatch/logs"
sbatch "$ROOT/sbatch/missing_defense/missing_defense_001_convnet_gradmatch_dog_bird_b0_02_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_002_convnet_gradmatch_dog_bird_b0_02_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_003_convnet_gradmatch_dog_bird_b0_02_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_004_convnet_gradmatch_dog_bird_b0_02_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_005_convnet_gradmatch_dog_bird_b0_02_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_006_convnet_gradmatch_dog_bird_b0_02_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_007_convnet_sapa_dog_bird_b0_02_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_008_convnet_sapa_dog_bird_b0_02_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_009_convnet_sapa_dog_bird_b0_02_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_010_convnet_sapa_dog_bird_b0_02_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_011_convnet_sapa_dog_bird_b0_02_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_012_convnet_sapa_dog_bird_b0_02_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_013_resnet20_fc_dog_bird_b0_01_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_014_resnet20_fc_dog_bird_b0_01_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_015_resnet20_gradmatch_dog_bird_b0_002_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_016_resnet20_gradmatch_dog_bird_b0_002_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_017_resnet20_gradmatch_dog_bird_b0_002_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_018_resnet20_gradmatch_dog_bird_b0_002_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_019_resnet20_gradmatch_dog_bird_b0_01_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_020_resnet20_gradmatch_dog_bird_b0_01_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_021_resnet20_gradmatch_dog_bird_b0_01_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_022_resnet20_gradmatch_dog_bird_b0_01_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_023_resnet20_gradmatch_dog_bird_b0_01_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_024_resnet20_gradmatch_dog_bird_b0_01_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_025_resnet20_sapa_dog_bird_b0_01_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_026_resnet20_sapa_dog_bird_b0_01_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_027_resnet20_sapa_dog_bird_b0_01_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_028_resnet20_sapa_dog_bird_b0_01_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_029_resnet20_sapa_dog_bird_b0_01_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_030_resnet20_sapa_dog_bird_b0_01_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_031_vgg13_gradmatch_dog_bird_b0_005_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_032_vgg13_gradmatch_dog_bird_b0_005_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_033_vgg13_gradmatch_dog_bird_b0_005_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_034_vgg13_gradmatch_dog_bird_b0_005_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_035_vgg13_gradmatch_dog_bird_b0_01_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_036_vgg13_gradmatch_dog_bird_b0_01_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_037_vgg13_gradmatch_dog_bird_b0_01_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_038_vgg13_gradmatch_dog_bird_b0_01_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_039_vgg13_gradmatch_dog_bird_b0_01_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_040_vgg13_gradmatch_dog_bird_b0_01_friends_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_041_vgg13_sapa_dog_bird_b0_005_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_042_vgg13_sapa_dog_bird_b0_005_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_043_vgg13_sapa_dog_bird_b0_005_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_044_vgg13_sapa_dog_bird_b0_005_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_045_vgg13_sapa_dog_bird_b0_01_epic_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_046_vgg13_sapa_dog_bird_b0_01_epic_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_047_vgg13_sapa_dog_bird_b0_01_epic_dpp_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_048_vgg13_sapa_dog_bird_b0_01_friends_ours_std.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_049_vgg13_sapa_dog_bird_b0_01_friends_ours_j.sh"
sleep 1
sbatch "$ROOT/sbatch/missing_defense/missing_defense_050_vgg13_sapa_dog_bird_b0_01_friends_dpp_j.sh"
sleep 1
